### ISSUE TITLE
[Common] jwt expire seconds 변경

### ISSUE THREAD

**Issue by hanjo8813** [prgrms-web-devcourse/Team_BbungCles_Devnity_BE#47]
```yml
jwt:
  header: Authentication
  issuer: ${JWT_ISSUER}
  client-secret: ${JWT_SECRET}
  expiry-seconds: ${JWT_EXPRIE}
```

다음과 같이 웬만한 jwt 관련 파라미터는 환경변수로 은닉하려 했으나.. 아래와 같은 오류 발생

<img width="802" alt="image" src="https://user-images.githubusercontent.com/71180414/145051855-6bb530c0-156b-4e4d-a548-5d26989d10ed.png">

환경변수로 주입되는 숫자를 문자로 인식하여 오류 발생
반드시 int 값만이 들어와야 한다는 것을 보면 환경변수 주입시 String으로 인식하는 것을 알 수 있음
( jwt 라이브러리에서 string을 int로 변환해주지 않나봄 ㅡㅡ)

따라서 환경변수 제거, 노출시켜 작성.....
